server:
  port: ${PORT}

  # error:
    # include-message: never
    # include-binding-errors: never
    # include-stacktrace: never

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddlAuto: update

  security:
    user:
      name: devansh
      password: devansh!

  mvc:
    throw-exception-if-no-handler-found: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka