server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: devansh
    password: devansh!
    driverClassName: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddlAuto: update

  security:
    user:
      name: devansh
      password: devansh!

  mvc:
    throw-exception-if-no-handler-found: false

eureka:
  instance:
    hostname: localhost
  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka